import { Guide, Phrase, HelpCenter, Restaurant, Hotel, DocumentProcedure, Translations } from './types';

export const GUIDES: Guide[] = [
  {
    id: 'patent',
    title: 'Оформление Патента',
    icon: 'FileBadge',
    description: 'Легализация трудовой деятельности',
    steps: [
      { id: 'p1', text: 'Пройти медицинское освидетельствование' },
      { id: 'p2', text: 'Сдать экзамен по русскому языку' },
      { id: 'p3', text: 'Оформить полис ДМС' },
      { id: 'p4', text: 'Оплатить налог (НДФЛ)' },
      { id: 'p5', text: 'Подать заявление в МВД' },
    ],
  },
  {
    id: 'rvp',
    title: 'РВП (Разрешение на проживание)',
    icon: 'Stamp',
    description: 'Первый шаг к гражданству',
    steps: [
      { id: 'r1', text: 'Получить квоту (если необходимо)' },
      { id: 'r2', text: 'Собрать справки об отсутствии судимости' },
      { id: 'r3', text: 'Пройти медкомиссию' },
      { id: 'r4', text: 'Подать заявление и ждать 60 дней' },
    ],
  },
  {
    id: 'vnj',
    title: 'ВНЖ (Вид на жительство)',
    icon: 'Landmark',
    description: 'Постоянное проживание',
    steps: [
      { id: 'v1', text: 'Прожить по РВП не менее 8 месяцев' },
      { id: 'v2', text: 'Подтвердить доход' },
      { id: 'v3', text: 'Оплатить госпошлину' },
    ],
  },
  {
    id: 'insurance',
    title: 'Медицинская страховка',
    icon: 'HeartPulse',
    description: 'Обязательно для всех иностранцев',
    steps: [
      { id: 'i1', text: 'Выбрать страховую компанию' },
      { id: 'i2', text: 'Выбрать тариф покрытия' },
      { id: 'i3', text: 'Оформить полис онлайн или в офисе' },
    ],
  },
];

export const PHRASES: Phrase[] = [
  // В Больнице
  { id: 'h1', category: 'В больнице', original: 'Мне нужен врач', translated: 'Маған дәрігер керек (Mağan däriger kerek)' },
  { id: 'h2', category: 'В больнице', original: 'У меня болит голова', translated: 'Басым ауырып тұр (Basym auyryp tұr)' },
  { id: 'h3', category: 'В больнице', original: 'Вызовите скорую', translated: 'Жедел жәрдем шақырыңыз (Jedel järdem şaqyryñyz)' },
  
  // В Полиции
  { id: 'p1', category: 'В полиции', original: 'Я потерял документы', translated: 'Мен құжаттарымды жоғалттым (Men qūjattarymdy joğalttym)' },
  { id: 'p2', category: 'В полиции', original: 'Где находится посольство?', translated: 'Елшілік қайда? (Elşilik qaida?)' },
  
  // Аренда
  { id: 'a1', category: 'Аренда жилья', original: 'Сколько стоит аренда?', translated: 'Жалға алу қанша тұрады? (Jalğa alu qanşa tұrady?)' },
  { id: 'a2', category: 'Аренда жилья', original: 'Включены ли коммунальные услуги?', translated: 'Коммуналдық қызметтер қосылған ба? (Kommunaldyq qyzmetter qosylğan ba?)' },
  
  // Работа
  { id: 'w1', category: 'Работа', original: 'Я ищу работу', translated: 'Мен жұмыс іздеп жүрмін (Men jūmys izdep jürmin)' },
  { id: 'w2', category: 'Работа', original: 'Когда зарплата?', translated: 'Жалақы қашан болады? (Jalaqy qaşan bolady?)' },
];

// Almaty Coordinates - Актуальные адреса полезных мест для мигрантов
export const HELP_CENTERS: HelpCenter[] = [
  // ЦОНы (Центры обслуживания населения)
  {
    id: 'c1',
    name: 'ЦОН Алмалинского района',
    type: 'mfc',
    address: 'ул. Толе би, 273А, блок 1, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 20:00, Сб: 09:00 - 13:00',
    lat: 43.2567,
    lng: 76.9425,
  },
  {
    id: 'c2',
    name: 'ЦОН Бостандыкского района',
    type: 'mfc',
    address: 'мкр. Көктем-3, 24, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 20:00, Сб: 09:00 - 13:00',
    lat: 43.2385,
    lng: 76.8875,
  },
  {
    id: 'c3',
    name: 'ЦОН Ауэзовского района',
    type: 'mfc',
    address: 'мкр. Жетысу-3, 5, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 20:00, Сб: 09:00 - 13:00',
    lat: 43.2156,
    lng: 76.8502,
  },
  {
    id: 'c4',
    name: 'ЦОН Алатауского района',
    type: 'mfc',
    address: 'мкр. Акбулак, 33/1, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 20:00, Сб: 09:00 - 13:00',
    lat: 43.1980,
    lng: 76.8015,
  },

  // Миграционная служба
  {
    id: 'c5',
    name: 'Управление миграционной службы г. Алматы',
    type: 'police',
    address: 'ул. Карасай батыра, 109А, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 17:30 (перерыв 13:00 - 14:30)',
    lat: 43.2498,
    lng: 76.9189,
  },
  {
    id: 'c6',
    name: 'Отдел миграционной полиции Бостандыкского района',
    type: 'police',
    address: 'ул. Василия Клочкова, 124, Алматы',
    workingHours: 'Пн-Сб: 09:00 - 17:30 (перерыв 13:00 - 14:30)',
    lat: 43.2445,
    lng: 76.8925,
  },

  // Центры поддержки мигрантов
  {
    id: 'c7',
    name: 'Центр поддержки мигрантов',
    type: 'legal',
    address: 'ул. Макатаева, 127/9, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 18:00',
    lat: 43.2365,
    lng: 76.9285,
  },

  // Больницы
  {
    id: 'c8',
    name: 'Городская поликлиника №1',
    type: 'hospital',
    address: 'ул. Толе би, 99, Алматы',
    workingHours: 'Пн-Пт: 08:00 - 20:00, Сб: 08:00 - 14:00',
    lat: 43.2587,
    lng: 76.9345,
  },
  {
    id: 'c9',
    name: 'Городская поликлиника №4',
    type: 'hospital',
    address: 'ул. Маметовой, 46, Алматы',
    workingHours: 'Пн-Пт: 08:00 - 20:00, Сб: 08:00 - 14:00',
    lat: 43.2425,
    lng: 76.9125,
  },
  {
    id: 'c10',
    name: 'Городская больница №7',
    type: 'hospital',
    address: 'мкр. Калкаман, 20, Алматы',
    workingHours: 'Круглосуточно',
    lat: 43.2185,
    lng: 76.8378,
  },
  {
    id: 'c11',
    name: 'Больница скорой помощи',
    type: 'hospital',
    address: 'ул. Жибек жолы, 119, Алматы',
    workingHours: 'Круглосуточно',
    lat: 43.2625,
    lng: 76.9475,
  },

  // Центры тестирования
  {
    id: 'c12',
    name: 'Центр тестирования по русскому языку',
    type: 'legal',
    address: 'пр. Абая, 8, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 18:00',
    lat: 43.2430,
    lng: 76.9550,
  },

  // Аптеки 24/7
  {
    id: 'c13',
    name: 'Аптека "Садр" (круглосуточная)',
    type: 'hospital',
    address: 'пр. Достык, 132, Алматы',
    workingHours: 'Круглосуточно',
    lat: 43.2365,
    lng: 76.9585,
  },
  {
    id: 'c14',
    name: 'Аптека "Европа" (круглосуточная)',
    type: 'hospital',
    address: 'ул. Фурманова, 219, Алматы',
    workingHours: 'Круглосуточно',
    lat: 43.2515,
    lng: 76.9425,
  },

  // Юридическая помощь
  {
    id: 'c15',
    name: 'Центр правовой помощи',
    type: 'legal',
    address: 'ул. Гоголя, 39, Алматы',
    workingHours: 'Пн-Пт: 09:00 - 18:00',
    lat: 43.2545,
    lng: 76.9385,
  },
];

// Restaurants with prices in all currencies
// Exchange rates (approximate): 1 USD = 450 KZT = 90 RUB = 5500 UZS = 11 TJS
export const RESTAURANTS: Restaurant[] = [
  // ============ BUDGET (Экономный) - до 5000 KZT ============
  {
    id: 'r1',
    name: 'Плов City',
    address: 'ул. Фурманова, 140, Алматы',
    cuisine: 'Узбекская',
    prices: { KZT: 2500, USD: 5.5, RUB: 500, UZS: 30000, TJS: 60 },
    budget: 'budget',
    phone: '+7 (727) 394-9494',
    lat: 43.2505,
    lng: 76.9415,
    rating: 4.5,
  },
  {
    id: 'r2',
    name: 'Samsa House',
    address: 'ул. Толе би, 286, Алматы',
    cuisine: 'Казахская',
    prices: { KZT: 1800, USD: 4, RUB: 360, UZS: 22000, TJS: 44 },
    budget: 'budget',
    lat: 43.2570,
    lng: 76.9420,
    rating: 4.3,
  },
  {
    id: 'r3',
    name: 'Ош Плов',
    address: 'пр. Достык, 85, Алматы',
    cuisine: 'Таджикская',
    prices: { KZT: 2200, USD: 5, RUB: 440, UZS: 27000, TJS: 54 },
    budget: 'budget',
    lat: 43.2365,
    lng: 76.9585,
    rating: 4.4,
  },
  {
    id: 'r4',
    name: 'Лапша Шен',
    address: 'ул. Макатаева, 128, Алматы',
    cuisine: 'Китайская',
    prices: { KZT: 3000, USD: 6.5, RUB: 600, UZS: 36000, TJS: 72 },
    budget: 'budget',
    lat: 43.2365,
    lng: 76.9285,
    rating: 4.2,
  },
  {
    id: 'r5',
    name: 'Столовая №1',
    address: 'ул. Абая, 52, Алматы',
    cuisine: 'Домашняя',
    prices: { KZT: 1500, USD: 3.3, RUB: 300, UZS: 18000, TJS: 36 },
    budget: 'budget',
    lat: 43.2400,
    lng: 76.9300,
    rating: 4.0,
  },
  {
    id: 'r6',
    name: 'Чайхана Бухара',
    address: 'ул. Гоголя, 54, Алматы',
    cuisine: 'Узбекская',
    prices: { KZT: 2800, USD: 6.2, RUB: 560, UZS: 34000, TJS: 68 },
    budget: 'budget',
    phone: '+7 (727) 250-1234',
    lat: 43.2480,
    lng: 76.9320,
    rating: 4.6,
  },
  {
    id: 'r7',
    name: 'Пельменная Сибирь',
    address: 'ул. Жибек Жолы, 115, Алматы',
    cuisine: 'Русская',
    prices: { KZT: 2000, USD: 4.4, RUB: 400, UZS: 24000, TJS: 48 },
    budget: 'budget',
    lat: 43.2550,
    lng: 76.9400,
    rating: 4.1,
  },
  {
    id: 'r8',
    name: 'Дастархан',
    address: 'ул. Шевченко, 90, Алматы',
    cuisine: 'Казахская',
    prices: { KZT: 3500, USD: 7.8, RUB: 700, UZS: 42000, TJS: 84 },
    budget: 'budget',
    lat: 43.2420,
    lng: 76.9380,
    rating: 4.4,
  },

  // ============ MEDIUM (Средний) - 5000-15000 KZT ============
  {
    id: 'r9',
    name: 'Arman',
    address: 'ул. Толе би, 95, Алматы',
    cuisine: 'Казахская / Европейская',
    prices: { KZT: 8500, USD: 19, RUB: 1700, UZS: 103000, TJS: 205 },
    budget: 'medium',
    phone: '+7 (727) 272-8080',
    lat: 43.2590,
    lng: 76.9340,
    rating: 4.5,
  },
  {
    id: 'r10',
    name: 'Gakku',
    address: 'ул. Жарокова, 227, Алматы',
    cuisine: 'Японская',
    prices: { KZT: 10000, USD: 22, RUB: 2000, UZS: 122000, TJS: 244 },
    budget: 'medium',
    lat: 43.2450,
    lng: 76.9500,
    rating: 4.7,
  },
  {
    id: 'r11',
    name: 'Terra Pizza',
    address: 'ул. Сауран, 12, Алматы',
    cuisine: 'Итальянская',
    prices: { KZT: 7000, USD: 15.5, RUB: 1400, UZS: 85000, TJS: 170 },
    budget: 'medium',
    website: 'terra.kz',
    lat: 43.2375,
    lng: 76.9275,
    rating: 4.4,
  },
  {
    id: 'r12',
    name: 'Душанбе',
    address: 'ул. Курмангазы, 88, Алматы',
    cuisine: 'Таджикская',
    prices: { KZT: 6000, USD: 13.3, RUB: 1200, UZS: 73000, TJS: 146 },
    budget: 'medium',
    phone: '+7 (727) 265-4545',
    lat: 43.2520,
    lng: 76.9380,
    rating: 4.3,
  },
  {
    id: 'r13',
    name: 'Ташкент',
    address: 'пр. Абылай хана, 64, Алматы',
    cuisine: 'Узбекская',
    prices: { KZT: 9000, USD: 20, RUB: 1800, UZS: 110000, TJS: 220 },
    budget: 'medium',
    lat: 43.2555,
    lng: 76.9465,
    rating: 4.6,
  },
  {
    id: 'r14',
    name: 'Burger King',
    address: 'пр. Достык, 111, Алматы',
    cuisine: 'Фастфуд',
    prices: { KZT: 5500, USD: 12.2, RUB: 1100, UZS: 67000, TJS: 134 },
    budget: 'medium',
    lat: 43.2380,
    lng: 76.9550,
    rating: 4.0,
  },
  {
    id: 'r15',
    name: 'Steak House',
    address: 'ул. Панфилова, 45, Алматы',
    cuisine: 'Американская',
    prices: { KZT: 12000, USD: 26.5, RUB: 2400, UZS: 146000, TJS: 292 },
    budget: 'medium',
    lat: 43.2500,
    lng: 76.9450,
    rating: 4.5,
  },
  {
    id: 'r16',
    name: 'Wok & Go',
    address: 'ул. Розыбакиева, 247, Алматы',
    cuisine: 'Азиатская',
    prices: { KZT: 6500, USD: 14.4, RUB: 1300, UZS: 79000, TJS: 158 },
    budget: 'medium',
    lat: 43.2300,
    lng: 76.9200,
    rating: 4.2,
  },

  // ============ PREMIUM (Премиум) - более 15000 KZT ============
  {
    id: 'r17',
    name: 'Khan Shatyry',
    address: 'пр. Достык, 132, Алматы',
    cuisine: 'Казахская / Европейская',
    prices: { KZT: 20000, USD: 44, RUB: 4000, UZS: 244000, TJS: 488 },
    budget: 'premium',
    phone: '+7 (727) 260-5555',
    lat: 43.2365,
    lng: 76.9585,
    rating: 4.8,
  },
  {
    id: 'r18',
    name: 'Seasons',
    address: 'ул. Валиханова, 74, Алматы',
    cuisine: 'Европейская',
    prices: { KZT: 18000, USD: 40, RUB: 3600, UZS: 220000, TJS: 440 },
    budget: 'premium',
    lat: 43.2315,
    lng: 76.9385,
    rating: 4.7,
  },
  {
    id: 'r19',
    name: 'Del Papa',
    address: 'ул. Кабанбай батыра, 87, Алматы',
    cuisine: 'Итальянская',
    prices: { KZT: 25000, USD: 55.5, RUB: 5000, UZS: 305000, TJS: 610 },
    budget: 'premium',
    phone: '+7 (727) 311-1111',
    lat: 43.2400,
    lng: 76.9500,
    rating: 4.9,
  },
  {
    id: 'r20',
    name: 'Sancak',
    address: 'пр. Аль-Фараби, 77, Алматы',
    cuisine: 'Турецкая',
    prices: { KZT: 16000, USD: 35.5, RUB: 3200, UZS: 195000, TJS: 390 },
    budget: 'premium',
    lat: 43.2200,
    lng: 76.9100,
    rating: 4.6,
  },
  {
    id: 'r21',
    name: 'Ristorante Buono',
    address: 'ул. Тулебаева, 38, Алматы',
    cuisine: 'Итальянская',
    prices: { KZT: 22000, USD: 49, RUB: 4400, UZS: 268000, TJS: 536 },
    budget: 'premium',
    website: 'buono.kz',
    lat: 43.2550,
    lng: 76.9350,
    rating: 4.8,
  },
  {
    id: 'r22',
    name: 'Nobu',
    address: 'пр. Достык, 200, Алматы',
    cuisine: 'Японская',
    prices: { KZT: 30000, USD: 66.5, RUB: 6000, UZS: 366000, TJS: 732 },
    budget: 'premium',
    lat: 43.2250,
    lng: 76.9550,
    rating: 4.9,
  },
];

// Document procedures - Процедуры оформления документов для мигрантов
export const DOCUMENT_PROCEDURES: DocumentProcedure[] = [
  {
    id: 'iin',
    title: 'Получение Индивидуального Идентификационного Номера (ИИН)',
    description: 'Необходимо всем иностранцам для легального проживания и работы в Казахстане',
    icon: 'Fingerprint',
    steps: [
      {
        id: 'iin1',
        title: 'Подготовка документов',
        description: 'Сготовьте паспорт, его нотариальный перевод на казахский и русский языки',
        location: 'Нотариус',
        duration: '1-2 дня',
      },
      {
        id: 'iin2',
        title: 'Обращение в ЦОН',
        description: 'Подайте документы в ЦОН по месту жительства',
        location: 'Центр обслуживания населения',
        duration: '30 минут',
      },
      {
        id: 'iin3',
        title: 'Получение ИИН',
        description: 'ИИН выдается в течение 3 рабочих дней',
        location: 'ЦОН',
        duration: '3 рабочих дня',
      },
    ],
    processingTime: '3-5 рабочих дней',
    requiredDocuments: ['Паспорт', 'Нотариальный перевод паспорта', 'Фото 3x4 (1 шт)'],
    cost: {
      amount: 10500,
      currency: 'KZT',
    },
  },
  {
    id: 'registration',
    title: 'Временная регистрация иностранца',
    description: 'Обязательная регистрация по месту проживания в течение 3 дней после прибытия',
    icon: 'FileText',
    steps: [
      {
        id: 'reg1',
        title: 'Найти жилье',
        description: 'Снять или арендовать помещение, получить подтверждение от хозяина',
        location: 'Жилое помещение',
        duration: '1-7 дней',
      },
      {
        id: 'reg2',
        title: 'Сбор документов',
        description: 'Подготовьте паспорт, миграционную карту, документ о жилье',
        location: 'Дома',
        duration: '1 день',
      },
      {
        id: 'reg3',
        title: 'Подача в ЦОН',
        description: 'Подайте документы в ЦОН по месту жительства',
        location: 'Центр обслуживания населения',
        duration: '30 минут',
      },
    ],
    processingTime: '1 рабочий день',
    requiredDocuments: ['Паспорт', 'Миграционная карта', 'Договор найма жилья или справка от хозяина'],
  },
  {
    id: 'rvp',
    title: 'Получение РВП (Разрешение на Временное Проживание)',
    description: 'Разрешение на проживание в Казахстане от 1 года до 3 лет',
    icon: 'Stamp',
    steps: [
      {
        id: 'rvp1',
        title: 'Определение типа РВП',
        description: 'Выберите основание: работа, учеба, воссоединение семьи, инвестиции',
        location: 'Миграционная служба',
        duration: '1 день',
      },
      {
        id: 'rvp2',
        title: 'Сбор документов',
        description: 'Соберите необходимый пакет документов в зависимости от типа РВП',
        location: 'Дома',
        duration: '3-5 дней',
      },
      {
        id: 'rvp3',
        title: 'Медицинское обследование',
        description: 'Пройдите медкомиссию (тест на туберкулез, ВИЧ и др.)',
        location: 'Медицинское учреждение',
        duration: '1-2 дня',
      },
      {
        id: 'rvp4',
        title: 'Подача заявления',
        description: 'Подайте документы в миграционную службу',
        location: 'Управление миграционной полиции',
        duration: '1 день',
      },
      {
        id: 'rvp5',
        title: 'Рассмотрение заявления',
        description: 'Ожидание решения - стандартно 60 дней',
        location: 'Миграционная служба',
        duration: '60 дней',
      },
    ],
    processingTime: '60-65 дней',
    requiredDocuments: [
      'Паспорт',
      'Анкета',
      'Фото (4 шт)',
      'Справка об отсутствии судимости',
      'Медицинская справка',
      'Документы в зависимости от основания',
    ],
    cost: {
      amount: 40700,
      currency: 'KZT',
    },
  },
  {
    id: 'vnzh',
    title: 'Получение ВНЖ (Вид на Жительство)',
    description: 'Постоянное проживание в Казахстане. Выдается на 5 лет',
    icon: 'Home',
    steps: [
      {
        id: 'vnzh1',
        title: 'Проживание по РВП',
        description: 'Прожить по РВП в Казахстане минимум 8 месяцев без нарушений',
        location: 'Казахстан',
        duration: '8 месяцев',
      },
      {
        id: 'vnzh2',
        title: 'Подтверждение дохода',
        description: 'Подготовьте доказательства стабильного дохода (справка с работы, налоговые документы)',
        location: 'Работодатель / Налоговые органы',
        duration: '1-2 дня',
      },
      {
        id: 'vnzh3',
        title: 'Сбор документов',
        description: 'Соберите необходимые документы для ВНЖ',
        location: 'Дома',
        duration: '2-3 дня',
      },
      {
        id: 'vnzh4',
        title: 'Подача заявления',
        description: 'Подайте документы в миграционную службу',
        location: 'Управление миграционной полиции',
        duration: '1 день',
      },
      {
        id: 'vnzh5',
        title: 'Получение ВНЖ',
        description: 'ВНЖ выдается в течение 17 дней (или 7 дней по ускоренной процедуре)',
        location: 'Миграционная служба',
        duration: '7-17 дней',
      },
    ],
    processingTime: '8 месяцев + 17 дней',
    requiredDocuments: [
      'Действующий РВП',
      'Паспорт',
      'Анкета',
      'Фото (4 шт)',
      'Справка о доходе',
      'Медицинская справка',
      'Подтверждение жилья',
    ],
    cost: {
      amount: 50700,
      currency: 'KZT',
    },
  },
  {
    id: 'patent',
    title: 'Трудовой патент для мигрантов',
    description: 'Разрешение на работу в Казахстане для граждан СНГ и других стран',
    icon: 'Briefcase',
    steps: [
      {
        id: 'patent1',
        title: 'Проверка здоровья',
        description: 'Пройти медицинское обследование (ВИЧ, туберкулез и др)',
        location: 'Медицинское учреждение',
        duration: '1-2 дня',
      },
      {
        id: 'patent2',
        title: 'Языковой тест',
        description: 'Сдать экзамен по русскому языку (минимум 50 баллов из 100)',
        location: 'Центр тестирования',
        duration: '1 день',
      },
      {
        id: 'patent3',
        title: 'Страховка',
        description: 'Оформить медицинскую страховку (полис ОМС)',
        location: 'Страховая компания / ЦОН',
        duration: '1 день',
      },
      {
        id: 'patent4',
        title: 'Оплата налога',
        description: 'Оплатить подоходный налог (НДФЛ)',
        location: 'Банк / ЦОН',
        duration: '1 день',
      },
      {
        id: 'patent5',
        title: 'Подача в МВД',
        description: 'Подать заявление на выдачу патента в МВД',
        location: 'Управление миграционной полиции',
        duration: '1 день',
      },
    ],
    processingTime: '10-15 рабочих дней',
    requiredDocuments: [
      'Паспорт',
      'Медицинская справка',
      'Сертификат о прохождении тестирования по русскому',
      'Полис страховки',
      'Квитанция об оплате налога',
    ],
    cost: {
      amount: 25700,
      currency: 'KZT',
    },
  },
];

// Hotels in Almaty with different budget categories
// Prices are per night
export const HOTELS: Hotel[] = [
  // ============ BUDGET (Бюджетные) - до 10000 KZT ============
  {
    id: 'h1',
    name: 'Хостел Central Inn',
    address: 'ул. Казыбек би, 142, Алматы',
    type: 'Хостел',
    prices: { KZT: 4000, USD: 9, RUB: 800, UZS: 49000, TJS: 98 },
    budget: 'budget',
    phone: '+7 (727) 291-3344',
    lat: 43.2560,
    lng: 76.9290,
    rating: 4.2,
    amenities: ['Wi-Fi', 'Общая кухня', 'Прачечная'],
  },
  {
    id: 'h2',
    name: 'Мини-отель Dostyk',
    address: 'ул. Достык, 104, Алматы',
    type: 'Мини-отель',
    prices: { KZT: 7500, USD: 17, RUB: 1500, UZS: 93000, TJS: 186 },
    budget: 'budget',
    phone: '+7 (727) 267-8899',
    lat: 43.2380,
    lng: 76.9480,
    rating: 4.0,
    amenities: ['Wi-Fi', 'Парковка', 'Кондиционер'],
  },
  {
    id: 'h3',
    name: 'Хостел Nomad',
    address: 'ул. Панфилова, 88, Алматы',
    type: 'Хостел',
    prices: { KZT: 3500, USD: 8, RUB: 700, UZS: 44000, TJS: 88 },
    budget: 'budget',
    phone: '+7 (727) 279-6655',
    lat: 43.2590,
    lng: 76.9450,
    rating: 4.3,
    amenities: ['Wi-Fi', 'Общая кухня', '24/7 ресепшн'],
  },
  {
    id: 'h4',
    name: 'Гостевой дом Алма',
    address: 'мкр. Самал-2, 58, Алматы',
    type: 'Гостевой дом',
    prices: { KZT: 8000, USD: 18, RUB: 1600, UZS: 99000, TJS: 198 },
    budget: 'budget',
    phone: '+7 (727) 263-4477',
    lat: 43.2440,
    lng: 76.9560,
    rating: 4.1,
    amenities: ['Wi-Fi', 'Кухня', 'Тихий район'],
  },
  {
    id: 'h5',
    name: 'Хостел Silk Road',
    address: 'ул. Гоголя, 127, Алматы',
    type: 'Хостел',
    prices: { KZT: 4500, USD: 10, RUB: 900, UZS: 55000, TJS: 110 },
    budget: 'budget',
    phone: '+7 (727) 291-5566',
    lat: 43.2570,
    lng: 76.9360,
    rating: 4.4,
    amenities: ['Wi-Fi', 'Прачечная', 'Общая зона отдыха'],
  },
  {
    id: 'h6',
    name: 'Мини-отель Комфорт',
    address: 'ул. Жарокова, 137, Алматы',
    type: 'Мини-отель',
    prices: { KZT: 9000, USD: 20, RUB: 1800, UZS: 110000, TJS: 220 },
    budget: 'budget',
    phone: '+7 (727) 394-2233',
    lat: 43.2510,
    lng: 76.9230,
    rating: 4.0,
    amenities: ['Wi-Fi', 'Парковка', 'Завтрак'],
  },

  // ============ MEDIUM (Средний класс) - 10000-25000 KZT ============
  {
    id: 'h7',
    name: 'Отель Kazzhol',
    address: 'пр. Абая, 62, Алматы',
    type: 'Отель',
    prices: { KZT: 15000, USD: 33, RUB: 3000, UZS: 183000, TJS: 366 },
    budget: 'medium',
    phone: '+7 (727) 292-7788',
    website: 'kazzhol-hotel.kz',
    lat: 43.2420,
    lng: 76.9640,
    rating: 4.3,
    amenities: ['Wi-Fi', 'Завтрак', 'Ресторан', 'Парковка', 'Кондиционер'],
  },
  {
    id: 'h8',
    name: 'Гостиница Otrar',
    address: 'ул. Гоголя, 73, Алматы',
    type: 'Гостиница',
    prices: { KZT: 18000, USD: 40, RUB: 3600, UZS: 220000, TJS: 440 },
    budget: 'medium',
    phone: '+7 (727) 293-1717',
    website: 'hotel-otrar.kz',
    lat: 43.2600,
    lng: 76.9400,
    rating: 4.2,
    amenities: ['Wi-Fi', 'Завтрак', 'Бассейн', 'Фитнес-центр', 'Сауна'],
  },
  {
    id: 'h9',
    name: 'Отель Uyut',
    address: 'ул. Толе би, 187, Алматы',
    type: 'Отель',
    prices: { KZT: 13500, USD: 30, RUB: 2700, UZS: 165000, TJS: 330 },
    budget: 'medium',
    phone: '+7 (727) 291-4455',
    lat: 43.2540,
    lng: 76.9350,
    rating: 4.1,
    amenities: ['Wi-Fi', 'Завтрак', 'Парковка', 'Конференц-зал'],
  },
  {
    id: 'h10',
    name: 'Гостиница Samal',
    address: 'мкр. Самал-3, 29, Алматы',
    type: 'Гостиница',
    prices: { KZT: 20000, USD: 44, RUB: 4000, UZS: 244000, TJS: 488 },
    budget: 'medium',
    phone: '+7 (727) 264-6677',
    website: 'samal-hotel.kz',
    lat: 43.2360,
    lng: 76.9600,
    rating: 4.4,
    amenities: ['Wi-Fi', 'Завтрак', 'Ресторан', 'Парковка', 'Круглосуточная стойка'],
  },
  {
    id: 'h11',
    name: 'Отель Grand Park',
    address: 'пр. Достык, 142, Алматы',
    type: 'Отель',
    prices: { KZT: 22000, USD: 49, RUB: 4400, UZS: 269000, TJS: 538 },
    budget: 'medium',
    phone: '+7 (727) 259-8877',
    website: 'grandpark-almaty.kz',
    lat: 43.2340,
    lng: 76.9620,
    rating: 4.5,
    amenities: ['Wi-Fi', 'Завтрак', 'Бассейн', 'Спа', 'Ресторан', 'Бар'],
  },
  {
    id: 'h12',
    name: 'Гостиница Kazakhstan',
    address: 'пр. Достык, 52/2, Алматы',
    type: 'Гостиница',
    prices: { KZT: 16500, USD: 37, RUB: 3300, UZS: 203000, TJS: 406 },
    budget: 'medium',
    phone: '+7 (727) 291-9988',
    website: 'hotel-kazakhstan.kz',
    lat: 43.2390,
    lng: 76.9510,
    rating: 4.2,
    amenities: ['Wi-Fi', 'Завтрак', 'Ресторан', 'Конференц-залы', 'Прачечная'],
  },

  // ============ PREMIUM (Премиум класс) - от 25000 KZT ============
  {
    id: 'h13',
    name: 'The Ritz-Carlton Almaty',
    address: 'пр. Достык, 8, Алматы',
    type: 'Отель 5*',
    prices: { KZT: 85000, USD: 189, RUB: 17000, UZS: 1037000, TJS: 2074 },
    budget: 'premium',
    phone: '+7 (727) 333-3333',
    website: 'ritzcarlton.com/almaty',
    lat: 43.2480,
    lng: 76.9420,
    rating: 4.9,
    amenities: ['Wi-Fi', 'Завтрак', 'Бассейн', 'Спа', 'Ресторан', 'Бар', 'Фитнес-центр', 'Консьерж'],
  },
  {
    id: 'h14',
    name: 'InterContinental Almaty',
    address: 'ул. Желтоксан, 181, Алматы',
    type: 'Отель 5*',
    prices: { KZT: 70000, USD: 156, RUB: 14000, UZS: 855000, TJS: 1710 },
    budget: 'premium',
    phone: '+7 (727) 505-0000',
    website: 'intercontinental.com/almaty',
    lat: 43.2530,
    lng: 76.9470,
    rating: 4.8,
    amenities: ['Wi-Fi', 'Завтрак', 'Бассейн', 'Спа', 'Ресторан', 'Бар', 'Конференц-залы'],
  },
  {
    id: 'h15',
    name: 'Rixos Almaty',
    address: 'ул. Сейфуллина, 506, Алматы',
    type: 'Отель 5*',
    prices: { KZT: 75000, USD: 167, RUB: 15000, UZS: 915000, TJS: 1830 },
    budget: 'premium',
    phone: '+7 (727) 300-3000',
    website: 'rixos.com/almaty',
    lat: 43.2500,
    lng: 76.9550,
    rating: 4.9,
    amenities: ['Wi-Fi', 'All Inclusive', 'Бассейн', 'Спа', 'Рестораны', 'Бар', 'Ночной клуб', 'Детский клуб'],
  },
  {
    id: 'h16',
    name: 'Royal Tulip Almaty',
    address: 'пр. Назарбаева, 127, Алматы',
    type: 'Отель 5*',
    prices: { KZT: 55000, USD: 122, RUB: 11000, UZS: 671000, TJS: 1342 },
    budget: 'premium',
    phone: '+7 (727) 357-5757',
    website: 'royaltulip-almaty.kz',
    lat: 43.2560,
    lng: 76.9380,
    rating: 4.7,
    amenities: ['Wi-Fi', 'Завтрак', 'Бассейн', 'Спа', 'Ресторан', 'Бар', 'Фитнес-центр'],
  },
  {
    id: 'h17',
    name: 'Novotel Almaty City Center',
    address: 'ул. Желтоксан, 89, Алматы',
    type: 'Отель 4*',
    prices: { KZT: 40000, USD: 89, RUB: 8000, UZS: 488000, TJS: 976 },
    budget: 'premium',
    phone: '+7 (727) 258-3000',
    website: 'novotel.com/almaty',
    lat: 43.2610,
    lng: 76.9430,
    rating: 4.6,
    amenities: ['Wi-Fi', 'Завтрак', 'Ресторан', 'Бар', 'Фитнес-центр', 'Парковка'],
  },
  {
    id: 'h18',
    name: 'Holiday Inn Almaty',
    address: 'пр. Абая, 14, Алматы',
    type: 'Отель 4*',
    prices: { KZT: 35000, USD: 78, RUB: 7000, UZS: 427000, TJS: 854 },
    budget: 'premium',
    phone: '+7 (727) 291-2020',
    website: 'holidayinn.com/almaty',
    lat: 43.2470,
    lng: 76.9520,
    rating: 4.5,
    amenities: ['Wi-Fi', 'Завтрак', 'Бассейн', 'Ресторан', 'Конференц-залы', 'Парковка'],
  },
];

// Translations for multi-language support
export const TRANSLATIONS: { [key: string]: Translations } = {
  ru: {
    nav: {
      dashboard: 'Главная',
      documents: 'Документы',
      guides: 'Инструкции',
      restaurants: 'Где поесть',
      procedures: 'Оформление',
      map: 'Карта помощи',
    },
    common: {
      language: 'Язык',
      budget: 'Бюджет',
      currency: 'Валюта',
      address: 'Адрес',
      phone: 'Телефон',
      working_hours: 'Часы работы',
    },
  },
  kk: {
    nav: {
      dashboard: 'Басты бет',
      documents: 'Құжаттар',
      guides: 'Нұсқаулықтар',
      restaurants: 'Нағдой ас',
      procedures: 'Ресімдеу',
      map: 'Көмек картасы',
    },
    common: {
      language: 'Тіл',
      budget: 'Бюджет',
      currency: 'Валюта',
      address: 'Мекенжайы',
      phone: 'Телефон',
      working_hours: 'Жұмыс уақыты',
    },
  },
  en: {
    nav: {
      dashboard: 'Home',
      documents: 'Documents',
      guides: 'Guides',
      restaurants: 'Dining',
      procedures: 'Procedures',
      map: 'Help Map',
    },
    common: {
      language: 'Language',
      budget: 'Budget',
      currency: 'Currency',
      address: 'Address',
      phone: 'Phone',
      working_hours: 'Working Hours',
    },
  },
  uz: {
    nav: {
      dashboard: 'Bosh sahifa',
      documents: 'Hujjatlar',
      guides: 'Ko\'rsatmalar',
      restaurants: 'Ovqat',
      procedures: 'Rasmiylashtirish',
      map: 'Yordam xritasi',
    },
    common: {
      language: 'Til',
      budget: 'Byudzhet',
      currency: 'Valyuta',
      address: 'Manzil',
      phone: 'Telefon',
      working_hours: 'Ishlash vaqti',
    },
  },
  tj: {
    nav: {
      dashboard: 'Саҳифаи асосӣ',
      documents: 'Ҳуҷҷатҳо',
      guides: 'Дастури',
      restaurants: 'Хури сичист',
      procedures: 'Раҷистрирон',
      map: 'Нақшаи кумак',
    },
    common: {
      language: 'Забон',
      budget: 'Бюджет',
      currency: 'Валюта',
      address: 'Суроғаи фалакат',
      phone: 'Телефон',
      working_hours: 'Вақти кор',
    },
  },
};
